# PostgreSQL. Versions 9.3 and up are supported.

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>
  port: <%= ENV['DB_PORT'] %> 

test:
  <<: *default
  database: rails_blog_test

production:
  <<: *default
  database: rails_blog_production
  username: rails_blog
  password: <%= ENV["RAILS_BLOG_DATABASE_PASSWORD"] %>
